### ISSUE TITLE
How do you calc the light bounce from the raymarch scene?

### ISSUE THREAD

**Issue by Yaazarai** [samuelbigos/godot_2d_global_illumination#1]
I've been looking around and I'm trying to do what you've done and develop my own 2D GI. Though I've gone a different path using polar-ray tracing with a dual pass shader: https://github.com/FatalSleep/2D-QuickRayTracing-GLSL

The efficiency of my algorithm is almost absurd, something in the order of thousands of lights depending on light radius. The problem is I don't have light bouncing, I'm not 100% sure on the approach I should use to calc it.

Any insight?

**Comment by samuelbigos** [comment]
Hey, I had a quick read of your approach and it looks interesting! There is a fundamental difference from what I've done in this repo though so I don't think the answer to your question will be of much use to you.

You're using light-to-object rays, whereas I use object-to-light rays. I've written a little intro to the approach [here](https://samuelbigos.github.io/posts/2dgi1-2d-global-illumination-in-godot.html), though it doesn't get to the point where I describe how light bouncing works. 

The tl;dr on the approach is that I cast rays out from every pixel in the scene, and if the ray hits an emissive surface, that surface contributes some of its light to the current pixel. The trick is that the input texture for sampling emissive values is the same as the output texture from the last frame. This means that effectively any surface can be a light/emissive source (and there's a mask to determine which surfaces can become emissive or not, e.g. a wall can become emissive while the floor cannot).

E.g. imagine a room with a single light in it. The light is a circle of pixels whose emissive value is 1. On the first frame, every pixel in the scene casts rays in all directions. Some might hit the light, in which case if it can become emissive (i.e. a wall) it inherits some of the light's emissive value. On the second frame, rays from other pixels can now hit those wall pixels and inherit the emissive value, and so on. That's how the light bounces work.

This relies on the fact that every pixel can effectively be a light source, and every pixel casts rays. I believe this is similar to the [Radiosity ](https://en.wikipedia.org/wiki/Radiosity_(computer_graphics))approach to global illumination if you want to read more into it.

Also, I will say I haven't touched 2DGI stuff for over a year so I might not be remembering everything 100% correctly :).

Good luck!

**Comment by Yaazarai** [comment]
I appreciate the insight, thank you!

**Comment by FatalSleep** [comment]
Also I don't know how much of a performance increase you could make, but you could probably add checks to improve performance to only perform pixel-ray casts within light distance to emissive objects.
